name: Verify KB integrity (reference/)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-kb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify manifest & previews vs repository content
        shell: bash
        run: |
          set -euo pipefail
          cd reference

          # Подсчёты по фактическому содержимому
          html_count=$(find pages -type f -name '*.html' | wc -l | tr -d ' ')
          har_count=$(find flows -type f -name '*.har' | wc -l | tr -d ' ')

          manifest_path="kb/manifest.json"
          if [[ -f "$manifest_path" ]]; then
            manifest_total=$(jq '.files|length' "$manifest_path")
          else
            manifest_total=0
          fi

          previews_dir="kb/previews_full"
          previews_exists="нет"
          if [[ -d "$previews_dir" ]] && [[ -n "$(ls -A "$previews_dir" 2>/dev/null || true)" ]]; then
            previews_exists="да"
          fi

          # Собираем список "сирот" (записаны в манифест, но файла нет)
          mapfile -t manifest_paths < <(jq -r '.files[].path' "$manifest_path" 2>/dev/null || true)
          missing=()
          for p in "${manifest_paths[@]:-}"; do
            [[ -e "$p" ]] || missing+=("$p")
          done

          # Отчёт – всегда со свежим штампом (чтобы был коммит)
          now="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          run_info="run_id=${GITHUB_RUN_ID}, run_number=${GITHUB_RUN_NUMBER}, sha=${GITHUB_SHA:0:7}"

          mkdir -p kb
          {
            echo "# Verify — проверка целостности базы знаний"
            echo "Дата: ${now}"
            echo
            echo "Запуск: ${run_info}"
            echo
            echo "## Сводка"
            echo "- HTML в репозитории: ${html_count}"
            echo "- HAR в репозитории: ${har_count}"
            echo "- Всего путей в manifest.json: ${manifest_total}"
            echo "- Папка превью существует и непуста: ${previews_exists}"
            echo
            if [[ ${#missing[@]} -eq 0 ]]; then
              echo "### Сироты манифеста (есть в manifest.json, но нет в репозитории)"
              echo "✅ Нет — все пути из манифеста найдены."
            else
              echo "### Сироты манифеста (есть в manifest.json, но нет в репозитории)"
              for x in "${missing[@]}"; do
                echo "- ${x}"
              done
            fi
          } > kb/verify.md

      - name: Commit verify report
        shell: bash
        run: |
          set -euo pipefail
          cd reference
          git config user.name "KB-bot"
          git config user.email "kb-bot@users.noreply.github.com"
          git add kb/verify.md
          # Коммит почти всегда будет, т.к. есть штамп запуска
          git commit -m "chore(kb): update verify report (run $GITHUB_RUN_ID)" || echo "nothing to commit"
          git push || true
